repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
        files: '.*\.(yaml|eyaml|yml)$'
      - id: check-toml
      - id: check-xml
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: '^[requirements]\.txt$'
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        files: '\.(py|sh|md|yaml)$'
      - id: remove-tabs
        files: '\.(py|sh|md|yaml)$'
        args: [ --whitespaces-count, '2' ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: markdown-toc
        args: [--indent, "    ", --bullets "-", -i]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.10.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: bundler-audit
      - id: check-mailmap
      - id: fasterer
      - id: forbid-binary
      - id: forbid-space-in-indent
        exclude: ^.*(?<!\.go)$
      - id: git-dirty
      - id: git-check
      - id: markdownlint
        exclude: ^CHANGELOG\.md$
      - id: reek
      - id: require-ascii
      - id: rubocop
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        args: [-e, SC2086]
      - id: shfmt
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v4.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']
